name: Build_Apk
 
on: 
 workflow_dispatch:
      inputs:
        package_name:
          description: This is just a test"
          required: true
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run : echo "this is a test for packaging apps"
    - run: chmod +x ./gradlew
    - run: ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: dump.apk
        path: out/magisk_module_release/
